### ISSUE TITLE
Volumes and Issue page

### ISSUE THREAD

**Issue by arjunkashyap** [SrirangaDigital/prabuddha-keralam#2]
Background white canvas should be included

**Comment by ananthmysore** [comment]
Background white Canvas included to volume and issue page.
![volume](https://cloud.githubusercontent.com/assets/7941834/5659837/e4d8f5f4-973e-11e4-907c-1f2d35a6cc2d.png)
![issue](https://cloud.githubusercontent.com/assets/7941834/5659838/e4e09052-973e-11e4-92b5-229f014284a5.png)
